### ISSUE TITLE
photon/command/auth.go:94: cannot refer to unexported name cli.context

### ISSUE THREAD

**Issue by Lokicity** [vmware/photon-controller-cli#2]
I got an email and somebody tried to modify the cli code and ran into this compiler err

photon/command/auth.go:94: cannot refer to unexported name cli.context
photon/command/auth.go:94: undefined: cli.context

The answer is that golang is case sensitive and you should use cli.Context instead of cli.context on line 94

**Comment by Anuj-21** [comment]
Thanks a lot for helping me.
