### ISSUE TITLE
Help regarding dubugging

### ISSUE THREAD

**Issue by Anuj-21** [vmware/photon-controller-cli#3]
Can you please tell which idle i can use for go,which provide me the functionality for building the project using "make" and also provide me the functionality to do a remote debugging and the steps to configure the idle.

**Comment by Lokicity** [comment]
@TheYorkWei

**Comment by AlainRoy** [comment]
I assume you mean IDE, not idle.

You can use any IDE you feel comfortable with. I know that some of us use Atom. (I do.)

Personally, I run the build from the command-line. It's only a single command to run, and it makes it easy to see all the output. 

Go doesn't provide a debugger. I'm not sure what you'd remotely debug--the CLI runs locally.
